from typing import Protocol
from .wallet import Wallet
__all__ = ["ICommandWalletRepository", "IQueryWalletRepository"]

class ICommandWalletRepository(Protocol):
    def get_wallet(self, user_id: str) -> Wallet | None: ...
    def save_wallet(self, wallet: Wallet) -> None: ...
    def save_wallets(self, *wallets: Wallet) -> None: ...


class IQueryWalletRepository(Protocol):
    def get_wallet_transactions(self): ...